import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Check, Heart } from "lucide-react";
import { Brand } from "@/components/digital-heroes";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Slider } from "@/components/ui/slider";
import { useState } from "react";

export const Route = createFileRoute("/signup")({ head: () => ({ meta: [{ title: "Join Digital Heroes" }, { name: "description", content: "Create your Digital Heroes membership and choose a cause to support." }, { property: "og:title", content: "Join Digital Heroes" }, { property: "og:description", content: "Play, win, and give back with one monthly membership." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: SignupPage });
function SignupPage(){const [percentage,setPercentage]=useState([15]); return <div className="min-h-screen hero-wash"><header className="mx-auto flex h-20 max-w-7xl items-center px-5 lg:px-8"><Brand/></header><main className="mx-auto grid max-w-6xl gap-10 px-5 py-10 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><div className="pt-7"><p className="text-xs font-extrabold uppercase text-primary">Hero membership</p><h1 className="mt-4 text-4xl font-extrabold leading-tight sm:text-5xl">Play for more than the score.</h1><p className="mt-5 leading-7 text-muted-foreground">£12 monthly. Cancel whenever you like. Your chosen giving percentage goes directly toward community impact.</p><div className="mt-9 grid gap-4">{["Automatic monthly draw entry","Track your latest Stableford scores","Choose and change your charity"].map(x=><div key={x} className="flex items-center gap-3 font-semibold"><span className="grid size-7 place-items-center rounded-full bg-success/15 text-success"><Check className="size-4"/></span>{x}</div>)}</div></div><form className="rounded-3xl border border-border bg-card p-6 premium-shadow sm:p-9" onSubmit={e=>e.preventDefault()}><div className="grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-sm font-bold sm:col-span-2">Full name<Input placeholder="Alex Morgan"/></label><label className="grid gap-2 text-sm font-bold sm:col-span-2">Email address<Input type="email" placeholder="alex@example.com"/></label><label className="grid gap-2 text-sm font-bold sm:col-span-2">Create password<Input type="password" placeholder="At least 8 characters"/></label><label className="grid gap-2 text-sm font-bold sm:col-span-2">Choose your charity<Select defaultValue="yoc"><SelectTrigger className="h-11 rounded-xl"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="yoc">Youth on Course UK</SelectItem><SelectItem value="mind">Mind</SelectItem><SelectItem value="water">WaterAid</SelectItem><SelectItem value="macmillan">Macmillan Cancer Support</SelectItem></SelectContent></Select></label><div className="sm:col-span-2 rounded-2xl bg-muted p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-2 font-bold"><Heart className="size-4 text-impact fill-current"/>Monthly contribution</div><span className="text-2xl font-extrabold text-primary">{percentage[0]}%</span></div><Slider value={percentage} min={10} max={50} step={5} onValueChange={setPercentage} className="mt-5"/><div className="mt-3 flex justify-between text-xs text-muted-foreground"><span>10% minimum</span><span>50% maximum</span></div></div></div><Button size="lg" className="mt-7 w-full">Create my membership <ArrowRight/></Button><p className="mt-5 text-center text-xs leading-5 text-muted-foreground">Prototype only — no payment will be taken.</p><p className="mt-5 text-center text-sm text-muted-foreground">Already a member? <Link to="/login" className="font-bold text-primary">Log in</Link></p></form></main></div>}